import { Formulario } from "@/entities/Formulario";
import { iRequestView } from "@/entities/Request";

export const homologateRequest = (formulario: Formulario): iRequestView => {
    return {
        createdAt: new Date(formulario.fecharegistro),
        channel: 'trad',
        name: formulario.nombrefuncionarioips,
        id: 0,
        radicate: (formulario.consecutivoradicado),
        programed_date: new Date(formulario.fechaprogramacion),
        address: formulario.direccion,
        phone: formulario.telefono1 ?? formulario.telefono2,
        estado: formulario.estado,
        document_number: Number(formulario.identificacion),
        document_type: formulario.tipodoc,
        lastname_1: formulario.apellido1,
        lastname_2: formulario.apellido2,
        firstname: formulario.nombre1,
        surname: formulario.nombre2,
        username: formulario.usuario,
        sede: formulario.sede,
        url_attachment: formulario.archivoadjunto,
        self_management_date: new Date(formulario.fechagestionautomatica),
        requested_number: (formulario.cantidadentrega),
        model_name: formulario.modelo,
        medicamento: String(formulario.medicamentoseleccionado).split("|")[0],
        plu: String(formulario.medicamentoseleccionado).split("|")[1],
        code: Number(formulario.medicamentoseleccionado.split("|")[2]),
        ips: String(formulario.epsseleccionado).split("|")[1],
        city: String(formulario.ciudadseleccionado).split("|")[1].toLowerCase(),
        department: String(formulario.ciudadseleccionado).split("|")[2].toLowerCase(),
        quantity: formulario.cantidadentrega,
        formula: formulario.numeroautorizacion,
        sended: new Date(formulario.fechasolicitud),
        scheduled: new Date(formulario.fechaprogramacion),
        digited: new Date(formulario.fechadispensacion),
        delivered: new Date(formulario.fechadispensacion),
        applied: new Date(formulario.fechadispensacion),
        guide_number: formulario.numeroguia,
        claimNumber: '',
        ips_delegate: formulario.nombrefuncionarioips,
        homologateId: formulario.incremento
    }
}